usudo: enabled

before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
        directories:
                - $HOME/.gradle/caches/
                - $HOME/.gradle/wrapper/

matrix:
        include:
                - language: android
                  jdk: oraclejdk8
                  android:
                          components:
                                  - tools
                                  - android-27
                                  - build-tools-28.0.3
                  before_script:
                          - cd ASE_android
                  script:
                          - gradle test androidTest      
